remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Shockprice.ai
description: Aplikasi web yang menggunakan input berupa gambar produk untuk membandingkan harga produk tersebut di berbagai marketplace daring
